osascript -e 'tell app "Terminal" to do script "cd '$PWD' && rm -R node_modules && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_0 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_1 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_2 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_3 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_4 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_5 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_6 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_7 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_8 && rm -R node_modules && rm flows.json && exit"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD'/data/data_9 && rm -R node_modules && rm flows.json && exit"'
