osascript -e 'tell app "Terminal" to do script "cd '$PWD' && npm install"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_0 --p 1990"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_1 --p 1991"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_2 --p 1992"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_3 --p 1993"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_4 --p 1994"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_5 --p 1995"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_6 --p 1996"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_7 --p 1997"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_8 --p 1998"'
osascript -e 'tell app "Terminal" to do script "cd '$PWD' && node node_modules/node-red/red.js --userDir '$PWD'/data_9 --p 1999"'