start "node-red-0-install" /D data_0 npm install
start "node-red-1-install" /D data_1 npm install
start "node-red-2-install" /D data_2 npm install
start "node-red-3-install" /D data_3 npm install
start "node-red-4-install" /D data_4 npm install
start "node-red-5-install" /D data_5 npm install
start "node-red-6-install" /D data_6 npm install
start "node-red-7-install" /D data_7 npm install
start "node-red-8-install" /D data_8 npm install
start "node-red-9-install" /D data_9 npm install