start "node-red-0" node node_modules/node-red/red.js --userDir ./data/data_0 --p 1990
start "node-red-1" node node_modules/node-red/red.js --userDir ./data/data_1 --p 1991
start "node-red-2" node node_modules/node-red/red.js --userDir ./data/data_2 --p 1992
start "node-red-2" node node_modules/node-red/red.js --userDir ./data/data_3 --p 1993
start "node-red-3" node node_modules/node-red/red.js --userDir ./data/data_4 --p 1994
start "node-red-5" node node_modules/node-red/red.js --userDir ./data/data_5 --p 1995
start "node-red-6" node node_modules/node-red/red.js --userDir ./data/data_6 --p 1996
start "node-red-7" node node_modules/node-red/red.js --userDir ./data/data_7 --p 1997
start "node-red-8" node node_modules/node-red/red.js --userDir ./data/data_8 --p 1998
start "node-red-9" node node_modules/node-red/red.js --userDir ./data/data_9 --p 1999